name: Audit

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build main
      run: pnpm build-main

    - name: Build types
      run: pnpm build-types

    - name: Build compat
      run: pnpm build-compat

    - name: Build package.json
      run: pnpm build-package-json

    - name: Archive compat
      run: tar --create --gzip --directory test --file compat.tgz compat

    - name: Upload compat
      uses: actions/upload-artifact@v4
      with:
        name: compat
        path: compat.tgz
        if-no-files-found: error

  validate:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint types
      run: pnpm lint-types

    - name: Lint code
      run: pnpm lint-code

    - name: Test package
      run: pnpm test

  compat:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download compat
      uses: actions/download-artifact@v4
      with:
        name: compat

    - name: Extract compat
      run: tar --extract --file *.tgz --strip-components 1

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install dependencies
      run: pnpm install --no-lockfile

    - name: Test package
      run: pnpm test
